-- Création du schéma DEPENSE_ODS
DROP SCHEMA IF EXISTS "DEPENSE_ODS";
CREATE SCHEMA "DEPENSE_ODS";

-- Création du schéma DEPENSE_DWH
DROP SCHEMA IF EXISTS "DEPENSE_DWH";
CREATE SCHEMA "DEPENSE_DWH";

-- Création du schéma PARAMS_LOG
DROP SCHEMA IF EXISTS "PARAMS_LOG";
CREATE SCHEMA "PARAMS_LOG";